### ISSUE TITLE
Code gets stuck in the StanfordCoreNLP call

### ISSUE THREAD

**Issue by vnik18** [sunyilgdx/SIFRank#2]
Hello, thank you for sharing your code. I am trying to run your code, and am stuck in the `Usage`section in the following line of code: 
`en_model = StanfordCoreNLP(‘stanford-corenlp-full-2018-02-27',quiet=True)`

The code simply 'hangs' or gets stuck in this line and does not move forward. The execution of this line does not finish even after waiting for a few hours. Can you please provide any help with this? Thank you

**Comment by sunyilgdx** [comment]
Maybe you should use the absolute path where your ‘stanford-corenlp’ located
