### ISSUE TITLE
Where or how did you get the file enwiki_vocab_min200.txt ?

### ISSUE THREAD

**Issue by vnik18** [sunyilgdx/SIFRank#3]
Thank you for sharing your code. A quick question: where or how did you get the file `enwiki_vocab_min200.txt` ? The one that is in the directory `auxiliary_data`.
Thank you.

**Comment by sunyilgdx** [comment]
From the [auxiliary_data](https://github.com/PrincetonML/SIF/tree/master/auxiliary_data) of the paper [*A Simple but Tough-to-Beat Baseline for Sentence Embeddings*](https://github.com/PrincetonML/SIF)

**Comment by zdaiot** [comment]
@sunyilgdx How about `auxiliary_data/inspec_vocab.txt`？thanks a lot
