### ISSUE TITLE
About the result of EmbedRank s2v

### ISSUE THREAD

**Issue by Asuna-Kawamura** [sunyilgdx/SIFRank#4]
Hi.
Thanks for your great work.
I check the paper which proposed EmbedRank, they use two different ways to generate the embedding: Sent2vec and Doc2vec. I find that the results of EmbedRank Sent2vec are better than Doc2vec on some datasets.
Did you compare EmbedRank Sent2vec on the SemEval2017 dataset?
Thanks
Kawamura

**Comment by sunyilgdx** [comment]
Sorry, we failed to use Sent2vec on Windows 10, so we didn't replicate and compare EmbedRank s2v. Maybe you can try on Linux or Mac OS.

**Comment by Asuna-Kawamura** [comment]
Sorry for my late reply.
I am going to try it on Linux.
Thank you very much!
