### ISSUE TITLE
实验结果不匹配

### ISSUE THREAD

**Issue by LinhanZ** [sunyilgdx/SIFRank#5]
你好，
我复现代码的结果与论文里面不太一样，在Semeval2017上面，elmo L0，lamda=0.6，N=5 的结果是f1@5 20.21, 与论文中22.59有一定差距，有可能是什么原因呢？

**Comment by sunyilgdx** [comment]
您好，有几点可能会影响结果，不同来源的ELMo模型和不同版本的Stanford CoreNLP，如果全部跟我的一致的话，由于没有不确定的因素，结果应该是一模一样的

**Comment by sunyilgdx** [comment]
> 你好，
> 我复现代码的结果与论文里面不太一样，在Semeval2017上面，elmo L0，lamda=0.6，N=5 的结果是f1@5 20.21, 与论文中22.59有一定差距，有可能是什么原因呢？

请问问题解决了吗，能不能提供更多您实验的信息，包括使用模型和CoreNLP的版本
