### ISSUE TITLE
evaluation question

### ISSUE THREAD

**Issue by dobby-seo** [sunyilgdx/SIFRank#6]
Thank you for great work!

However, your paper said using macro F1 score. But i know real implementation is micro avg f1 score not macro.
Isn't right macro needs average f1 score each document?

https://github.com/sunyilgdx/SIFRank/blob/274d84b797c449e66c414d887f15d9b40114c746/eval/sifrank_eval.py#L120

**Comment by sunyilgdx** [comment]
Sorry, there is an error here, we do use micro-F1(wrong in the paper). The metrics (micro-P-R-F1) we using are following previou works, such as Zhiyuan Liu's works[1](https://aclanthology.org/C12-1105.pdf), [2](https://aclanthology.org/D10-1036.pdf)
I apologize again for troubling you with your reading.

**Comment by dobby-seo** [comment]
@sunyilgdx 
Thanks to reply! It's okay, i can aware from this performance is better than others using macro-avg :D.

**Comment by dobby-seo** [comment]
@sunyilgdx 
I reopened this issue, because there are some mistake i think.
your evaluation metric doesn't consider duplicate candidate. https://arxiv.org/abs/1810.05241, generative model restrain duplicate keyphrase in this paper, but extractive model not.

So It's appeared that model extracted same keyphrase in several times. So It seems like precision is better that other papers. How do you think this?

I tested chunking noun phrases using stanford corenlp if duplicate pharse in document.
![image](https://user-images.githubusercontent.com/33983084/130161904-d4f70fd1-51d5-4b8f-9c41-c4a86493439e.png)

And how about using intersection?

Thanks.

**Comment by sunyilgdx** [comment]
Good question, but since time has passed for a long time, I can't remember some details, let me check it out. But all of our baselines use the same evaluation method and word segmentation tool (Stanford CoreNLP). I can upload the reproduction code of the baseline model first.

**Comment by sunyilgdx** [comment]
You can check out this [code](https://github.com/sunyilgdx/SIFRank/blob/274d84b797c449e66c414d887f15d9b40114c746/model/method.py#L112)
The function `get_final_dist(dist_all, method='average')` will filt the duplicate keyphrase.

**Comment by dobby-seo** [comment]
Thanks to kind reply!

I miss that function, it control duplicate using dictionary keys!
