### ISSUE TITLE
模型增强

### ISSUE THREAD

**Issue by DexterXu7023** [sunyilgdx/SIFRank#8]
您好，非常感谢您的工作。近期通过替换 SIFRank中的elmo预训练模型（例如electra，bert），做了一些对比实践，但发现差距较大，不知道什么原因。其次如果其他的预训练模型的确表现不如传统的Elmo，那SIFRank方法进一步提升的可能性在什么方面？

**Comment by sunyilgdx** [comment]
我论文里也做了实验，我个人认为是BERT类模型的不适合直接用来做文本表示，可以参考[苏神的分析](https://kexue.fm/archives/8069)。这方面的研究有很多，可以多看一看。

**Comment by DexterXu7023** [comment]
> 我论文里也有一个实验，我个人认为是 BERT 类模型的不适合直接制作文本，可以参考[苏神的分析](https://kexue.fm/archives/8069)。这方面的研究有很多，可以多看一看。

**Comment by DexterXu7023** [comment]
感谢您的回复
